### ISSUE TITLE
[VS2015] ccrewrite fails when `Expression` is used in a precondition

### ISSUE THREAD

**Issue by SergeyTeplyakov** [Microsoft/CodeContracts#133]
Following code works fine in VS2013 but fails to compile in VS2015:

```c#
public class WithExpressions
{
    public void A(bool expected)
    {
        Contract.Requires(P1<string, string>(x => x, expected));
    }

    public void A2(bool expected)
    {
        Contract.Requires(P1<string, string>(x => x, expected));
        Contract.Requires(P1<string, string>(x => x, expected));
    }

    public void A3(bool expected)
    {
        Contract.Requires(P1<string, string>(x => x, expected));
        bool r = P1<string, string>(x => x, expected);
    }        
}
```

The error from ccrewrite is:

```
Tests\RoslynCompatibility\ExpressionsInRequires.cs(36,3) : error CC1040: Reuse of existing local variable 'local0' in contract.
Tests\RoslynCompatibility\ExpressionsInRequires.cs(41,3) : error CC1025: After contract block, found use of local variable 'local1' defined in contract block
Tests\RoslynCompatibility\ExpressionsInRequires.cs(30,3) : error CC1004: Malformed contract. Found Requires after assignment in method 'Tests.Sources.WithExpressions.A(System.Boolean)'.
```

Please note, that the error would happen only for `Expression<Func<..>>` but not for lambda expression convertible to `Func<..>`.

**Comment by SergeyTeplyakov** [comment]
Fixed version could be found here: http://files.rsdn.ru/34036/ccrewrite.zip

Steps to use it: 1. Download; 2. Rename *.zip to *.exe; 3. Replace original ccrewrite.exe with this one at ProgramFiles32/Microsoft/Contracts/Bin.

**Comment by IharBury** [comment]
The fixed ccrewrite works fine. However, note that cccheck is also affected (it produces warnings with same error numbers and texts).

**Comment by SergeyTeplyakov** [comment]
@IharBury I'll publish new release with this fix soon.

**Comment by DzonnyDZ** [comment]
I tried the fixed ccrewrite, but it didn't help me. I'm still getting the error on code like this.
```C#
public void MoveFilesToAccessibleStorage(string ugcTempFolderLocal, string ugcTempFolderRemote, string appDrive)
        {
            Contract.Requires<ArgumentNullException>(ugcTempFolderLocal != null, "ugcTempFolder");
            Contract.Requires<ArgumentException>(ugcTempFolderLocal != string.Empty);
            Contract.Requires<ArgumentException>(!ugcTempFolderLocal.Contains(IO.Path.GetInvalidPathChars()));
            Contract.Requires<ArgumentException>(!ugcTempFolderLocal.Contains(":"));
            Contract.Requires<ArgumentException>(!ugcTempFolderLocal.EndsWith("\\") && !ugcTempFolderLocal.EndsWith("/"), "Do not provide trailing slashes for folder names");
            Contract.Requires<ArgumentException>(!ugcTempFolderLocal.StartsWith("\\", "/") || ugcTempFolderLocal.StartsWith("\\\\", "//", "\\/", "/\\"));
            Contract.Requires<ArgumentNullException>(appDrive != null, "appDrive");
            FileSystemHelper.ContractRequireRelativeFolderName(ugcTempFolderRemote);
            Contract.Requires<ArgumentException>(appDrive.Like("[A-Za-z]:\\"));
        }
```
on the line
```C#
Contract.Requires<ArgumentException>(!ugcTempFolderLocal.StartsWith("\\", "/") || ugcTempFolderLocal.StartsWith("\\\\", "//", "\\/", "/\\"));
```
20>C:\Pangea\common\RFERL.IBll\Backend\IAudioOperations.cs(116,13): error CC1004: Malformed contract. Found Requires after assignment in method 'RFERL.Bll.Backend.IAudioOperationsContract.MoveFilesToAccessibleStorage(System.String,System.String,System.String)'.

**Comment by SergeyTeplyakov** [comment]
Thanks for another test case. My fix was specifically for expressions, and your case is different. Will take a look at it soon.

**Comment by DzonnyDZ** [comment]
Thank you Sergey!
Shall I fill in a new bug for that?
